// LocalStorage
export const STORAGE_KEY = 'WEATHER'
export const APPID = '3897463698fab29cbf0f47eca9ac50d5'
// List
export const CREATE_LIST = 'LIST/CREATE_LIST'
export const DELETE_LIST = 'LIST/DELETE_LIST'
export const RENAME_LIST = 'LIST/RENAME_LIST'
// Todo
export const ADD_TODO = 'TODO/ADD_TODO'
export const DELETE_TODO = 'TODO/DELETE_TODO'
export const COMPLETED_TODO = 'TODO/COMPLETED_TODO'
//Weather
export const GET_WEATHER_REQUEST = 'WEATHER/GET_WEATHER_REQUEST'
export const GET_WEATHER_SUCCESS = 'WEATHER/GET_WEATHER_SUCCESS'
export const GET_WEATHER_FAILURE = 'WEATHER/GET_WEATHER_FAILURE'
